### PR TITLE
Better formatting of multiallelic variants for BSVI

### PR DESCRIPTION
**Pull request by jethror1**
- added some extra cutting up with `sed` to fully split multi allelic records to individual lines, should now allow bsvi to correctly calculate VAF for each alt

---
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/mutect2_vcf_2_bsvi/10)

### CODE REVIEW

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/mutect2_vcf_2_bsvi/10)* status: all files reviewed, 1 unresolved discussion (waiting on @jethror1)

___
*[bin/mutect2_vcf_2_BSVI_v1.1.1.py, line 41 at r1](https://reviewable.io/reviews/eastgenomics/mutect2_vcf_2_bsvi/10#-MXlWUjP84k1u3r5oZQi:-MXlWUjQ7EDz9O8WJRw1:bclqibq) ([raw file](https://github.com/eastgenomics/mutect2_vcf_2_bsvi/blob/d6617a29a7f26bb29ebc515788830468aef98692/bin/mutect2_vcf_2_BSVI_v1.1.1.py#L41)):*
> ```
>         f"zcat {input_vcf} | sed 's/AD,Number=./AD,Number=R/g' | "
>         "sed 's/RPA,Number=./RPA,Number=R/g' | "
> ```
Do we want to do a global replace here?
Might also be better to use `FORMAT=<ID=AD,Number=.` / `FORMAT=<ID=AD,Number=R` to add more specificity

**Review by jethror1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/mutect2_vcf_2_bsvi/10)* status: all files reviewed, 1 unresolved discussion (waiting on @carmelinacharalambous and @woook)

___
*[bin/mutect2_vcf_2_BSVI_v1.1.1.py, line 41 at r1](https://reviewable.io/reviews/eastgenomics/mutect2_vcf_2_bsvi/10#-MXlWUjP84k1u3r5oZQi:-MXmHOOc60nL2JY5wiWz:br8fo02) ([raw file](https://github.com/eastgenomics/mutect2_vcf_2_bsvi/blob/d6617a29a7f26bb29ebc515788830468aef98692/bin/mutect2_vcf_2_BSVI_v1.1.1.py#L41)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
>         f"zcat {input_vcf} | sed 's/AD,Number=./AD,Number=R/g' | "
>         "sed 's/RPA,Number=./RPA,Number=R/g' | "
> ```
Do we want to do a global replace here?
Might also be better to use `FORMAT=<ID=AD,Number=.` / `FORMAT=<ID=AD,Number=R` to add more specificity
</blockquote></details>

@woook @carmelinacharalambous thoughts on this?

**Comment by carmelinacharalambous** [comment]
___
*[bin/mutect2_vcf_2_BSVI_v1.1.1.py, line 41 at r1](https://reviewable.io/reviews/eastgenomics/mutect2_vcf_2_bsvi/10#-MXlWUjP84k1u3r5oZQi:-MXmSEeJ3j7Ce-w6pjzE:b4gio4l) ([raw file](https://github.com/eastgenomics/mutect2_vcf_2_bsvi/blob/d6617a29a7f26bb29ebc515788830468aef98692/bin/mutect2_vcf_2_BSVI_v1.1.1.py#L41)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

@woook @carmelinacharalambous thoughts on this?
</blockquote></details>

makes sense to add FORMAT=<ID=AD,Number=. / FORMAT=<ID=AD,Number=R for more specificity. unsure about global replace

**Review by jethror1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/mutect2_vcf_2_bsvi/10)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @mattgarner and @woook)

___
*[bin/mutect2_vcf_2_BSVI_v1.1.1.py, line 41 at r1](https://reviewable.io/reviews/eastgenomics/mutect2_vcf_2_bsvi/10#-MXlWUjP84k1u3r5oZQi:-MXmXgw84N1icXjqA42v:b-4frn6z) ([raw file](https://github.com/eastgenomics/mutect2_vcf_2_bsvi/blob/d6617a29a7f26bb29ebc515788830468aef98692/bin/mutect2_vcf_2_BSVI_v1.1.1.py#L41)):*
<details><summary><i>Previously, carmelinacharalambous wrote…</i></summary><blockquote>

makes sense to add FORMAT=<ID=AD,Number=. / FORMAT=<ID=AD,Number=R for more specificity. unsure about global replace
</blockquote></details>

Have changed to use `FORMAT=` to the AD field and `INFO=` for the RPA field, is this correct @mattgarner ?

**Review by mattgarner — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/mutect2_vcf_2_bsvi/10)* status: all files reviewed, 1 unresolved discussion (waiting on @woook)

**Review by mattgarner — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/mutect2_vcf_2_bsvi/10)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jethror1)

**Comment by woook** [comment]
Sorry I meant to look at this before but didn't get round to it.

1. Changing the `AD` `Number` `R` means that every allele should have a value for AD (whereas `.` means that the number of values is undetermined. Do we know whether there will always be an `AD` for every allele? What would happen with the downstream bcftools commands if every allele didn't have an `AD`? Could check that the number or `AD`'s = the number of alleles before making this change?
2. Same question for RPA. Also, perhaps it might be better to leave RPA alone seeing as it's field that we don't use?

**Pull request merged**
