### PR TITLE
Updated version 1.1.0

### PR DESCRIPTION
**Pull request by carmelinacharalambous**
#### Includes the following changes: ####

* renames output vcf instead of adding a _multiallelic_split suffix a _ms suffix is added
* removes ngr_ prefix from output vcf

#### The output vcf name had to be shorten due to the BSVI 100 character limit ####

---
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/mutect2_vcf_2_bsvi/5)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/mutect2_vcf_2_bsvi/5)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @carmelinacharalambous)

___
*[bin/mutect2_vcf_2_BSVI_v1.1.0.py, line 95 at r1](https://reviewable.io/reviews/eastgenomics/mutect2_vcf_2_bsvi/5#-MWPJdka9mM4BvGUwEso:-MWPJdka9mM4BvGUwEsp:bzhp3kd) ([raw file](https://github.com/eastgenomics/mutect2_vcf_2_bsvi/blob/5463d832ac5df6c6c746ee6d91ad2f8e5de2108a/bin/mutect2_vcf_2_BSVI_v1.1.0.py#L95)):*
> ```Python
>     # set name for output vcf from input
>     fname = str(Path(input_vcf).name).replace(
>         '.vcf', '_ms').rstrip('.gz').strip('ngr_')
> ```

where abouts is `ngr_` added to the file name?

If it is in the middle of the name you will need to use `.replace()` as `.strip()` only strips from the ends of a string, i.e. `.replace('ngr_', '')`

**Comment by carmelinacharalambous** [comment]
___
*[bin/mutect2_vcf_2_BSVI_v1.1.0.py, line 95 at r1](https://reviewable.io/reviews/eastgenomics/mutect2_vcf_2_bsvi/5#-MWPJdka9mM4BvGUwEso:-MWPNcpY7D_FTAkGkmkS:b-co8s1x) ([raw file](https://github.com/eastgenomics/mutect2_vcf_2_bsvi/blob/5463d832ac5df6c6c746ee6d91ad2f8e5de2108a/bin/mutect2_vcf_2_BSVI_v1.1.0.py#L95)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

where abouts is `ngr_` added to the file name?

If it is in the middle of the name you will need to use `.replace()` as `.strip()` only strips from the ends of a string, i.e. `.replace('ngr_', '')`
</blockquote></details>

will update PR to accommodate for this

**Review by jethror1 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/mutect2_vcf_2_bsvi/5)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @carmelinacharalambous)

**Review by jethror1 — APPROVED** [review]
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/mutect2_vcf_2_bsvi/5)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @carmelinacharalambous)

**Pull request merged**
