### PR TITLE
working release

### PR DESCRIPTION
**Pull request by jethror1**
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/mutect2_vcf_2_bsvi/1)

### CODE REVIEW

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/mutect2_vcf_2_bsvi/1)* status: all files reviewed, 3 unresolved discussions (waiting on @jethror1 and @woook)

___
*[README.md, line 17 at r2](https://reviewable.io/reviews/eastgenomics/mutect2_vcf_2_bsvi/1#-MVaqYtpEndH85DlIKeW:-MVaqYtpEndH85DlIKeX:b-2dkubn) ([raw file](https://github.com/eastgenomics/mutect2_vcf_2_bsvi/blob/445a956d4024b8a76ba5345f0f2f9af2385a1b24/README.md#L17)):*
> ```
> biallelic records using [bcftools norm][bcftools-url], then modifies genotype
> entries to `0/1`.
> ```
Would it be better to set these to `./1` ?

Considering a case where the genotype is `1/2/3`, this becomes three `0/1` variants
However the sample contains no ref allele, so the 0 in `0/1` is potentially misleading
Using `.` to signify that the info for a second allele is missing seems less wrong than stating that it's ref

Of course if this doesn't work for BSVI then it cannot be considered.
___
*[bin/mutect2_vcf_2_BSVI.py, line 43 at r2](https://reviewable.io/reviews/eastgenomics/mutect2_vcf_2_bsvi/1#-MVasDjd8WHCUDBov6or:-MVasDjd8WHCUDBov6os:bofb03z) ([raw file](https://github.com/eastgenomics/mutect2_vcf_2_bsvi/blob/445a956d4024b8a76ba5345f0f2f9af2385a1b24/bin/mutect2_vcf_2_BSVI.py#L43)):*
> ```
> strip('"\n')
> ```
An explanatory comment might be useful here
___
*[bin/mutect2_vcf_2_BSVI.py, line 117 at r2](https://reviewable.io/reviews/eastgenomics/mutect2_vcf_2_bsvi/1#-MVavIw13ko7f43QM40M:-MVavIw13ko7f43QM40N:b2dc1qo) ([raw file](https://github.com/eastgenomics/mutect2_vcf_2_bsvi/blob/445a956d4024b8a76ba5345f0f2f9af2385a1b24/bin/mutect2_vcf_2_BSVI.py#L117)):*
> ```
>     # check only one vcf passed
>     assert len(sys.argv) <= 2, 'More than one VCF passed.'
> ```
Checks that less than 2 files were passed, but does not check that only 1 was passed (what about 0 files)

Would `assert len(sys.argv) == 1` be better?

Not super important in the context of an app since you will control number of inputs passed to this elsewhere

**Review by jethror1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/mutect2_vcf_2_bsvi/1)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @mattgarner and @woook)

___
*[README.md, line 17 at r2](https://reviewable.io/reviews/eastgenomics/mutect2_vcf_2_bsvi/1#-MVaqYtpEndH85DlIKeW:-MVb06KTEmUJneBCza13:b45rpmj) ([raw file](https://github.com/eastgenomics/mutect2_vcf_2_bsvi/blob/445a956d4024b8a76ba5345f0f2f9af2385a1b24/README.md#L17)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> biallelic records using [bcftools norm][bcftools-url], then modifies genotype
> entries to `0/1`.
> ```
Would it be better to set these to `./1` ?

Considering a case where the genotype is `1/2/3`, this becomes three `0/1` variants
However the sample contains no ref allele, so the 0 in `0/1` is potentially misleading
Using `.` to signify that the info for a second allele is missing seems less wrong than stating that it's ref

Of course if this doesn't work for BSVI then it cannot be considered.
</blockquote></details>

I can change this if needed, @woook do you know if BSVI accepts `./1`?
___
*[bin/mutect2_vcf_2_BSVI.py, line 43 at r2](https://reviewable.io/reviews/eastgenomics/mutect2_vcf_2_bsvi/1#-MVasDjd8WHCUDBov6or:-MVb-rgY74jK-_N-6qtW:b-ebkatr) ([raw file](https://github.com/eastgenomics/mutect2_vcf_2_bsvi/blob/445a956d4024b8a76ba5345f0f2f9af2385a1b24/bin/mutect2_vcf_2_BSVI.py#L43)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
> strip('"\n')
> ```
An explanatory comment might be useful here
</blockquote></details>

wasn't actually needed, now removed
___
*[bin/mutect2_vcf_2_BSVI.py, line 117 at r2](https://reviewable.io/reviews/eastgenomics/mutect2_vcf_2_bsvi/1#-MVavIw13ko7f43QM40M:-MVay88_9y6l0cOtCaAN:bwbvswl) ([raw file](https://github.com/eastgenomics/mutect2_vcf_2_bsvi/blob/445a956d4024b8a76ba5345f0f2f9af2385a1b24/bin/mutect2_vcf_2_BSVI.py#L117)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
>     # check only one vcf passed
>     assert len(sys.argv) <= 2, 'More than one VCF passed.'
> ```
Checks that less than 2 files were passed, but does not check that only 1 was passed (what about 0 files)

Would `assert len(sys.argv) == 1` be better?

Not super important in the context of an app since you will control number of inputs passed to this elsewhere
</blockquote></details>

`sys.argv[0]` is the script which would have length of 1, so would need to assert it is 2. I did `<=2` as running it without any input wouldn't be the correct message, can just change it to `Requires just one VCF to be passed` or something

**Review by jethror1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/mutect2_vcf_2_bsvi/1)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @mattgarner and @woook)

___
*[bin/mutect2_vcf_2_BSVI.py, line 43 at r2](https://reviewable.io/reviews/eastgenomics/mutect2_vcf_2_bsvi/1#-MVasDjd8WHCUDBov6or:-MVb1ckB9PXwdBmnuuZ7:b-896fix) ([raw file](https://github.com/eastgenomics/mutect2_vcf_2_bsvi/blob/445a956d4024b8a76ba5345f0f2f9af2385a1b24/bin/mutect2_vcf_2_BSVI.py#L43)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

wasn't actually needed, now removed
</blockquote></details>

Done.
___
*[bin/mutect2_vcf_2_BSVI.py, line 117 at r2](https://reviewable.io/reviews/eastgenomics/mutect2_vcf_2_bsvi/1#-MVavIw13ko7f43QM40M:-MVb1cEL6DkUUes7RPWP:b-896fix) ([raw file](https://github.com/eastgenomics/mutect2_vcf_2_bsvi/blob/445a956d4024b8a76ba5345f0f2f9af2385a1b24/bin/mutect2_vcf_2_BSVI.py#L117)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

`sys.argv[0]` is the script which would have length of 1, so would need to assert it is 2. I did `<=2` as running it without any input wouldn't be the correct message, can just change it to `Requires just one VCF to be passed` or something
</blockquote></details>

Done.

**Review by woook — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/mutect2_vcf_2_bsvi/1)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @mattgarner)

___
*[README.md, line 17 at r2](https://reviewable.io/reviews/eastgenomics/mutect2_vcf_2_bsvi/1#-MVaqYtpEndH85DlIKeW:-MVbHl1H318Kgy9oQMT9:bg4kxr7) ([raw file](https://github.com/eastgenomics/mutect2_vcf_2_bsvi/blob/445a956d4024b8a76ba5345f0f2f9af2385a1b24/README.md#L17)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

I can change this if needed, @woook do you know if BSVI accepts `./1`?
</blockquote></details>

I've put ./1 into BSVI and it accepts it. 
It treats it as 0 though so looks the same as 0/1 in BSVi - however, I agree that it would be less wrong in the VCF to have ./1

As long as ./1 doesn't break anything else.

**Review by mattgarner — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/mutect2_vcf_2_bsvi/1)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @jethror1 and @mattgarner)

___
*[bin/mutect2_vcf_2_BSVI.py, line 117 at r2](https://reviewable.io/reviews/eastgenomics/mutect2_vcf_2_bsvi/1#-MVavIw13ko7f43QM40M:-MVbMYz15Ai2nSXgBA_h:boo8usk) ([raw file](https://github.com/eastgenomics/mutect2_vcf_2_bsvi/blob/445a956d4024b8a76ba5345f0f2f9af2385a1b24/bin/mutect2_vcf_2_BSVI.py#L117)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

:facepalm: I cannot count :)

**Review by mattgarner — COMMENTED** [review]
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/mutect2_vcf_2_bsvi/1)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @mattgarner)

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/mutect2_vcf_2_bsvi/1)* status: all files reviewed, 1 unresolved discussion (waiting on @jethror1 and @woook)

___
*[README.md, line 17 at r2](https://reviewable.io/reviews/eastgenomics/mutect2_vcf_2_bsvi/1#-MVaqYtpEndH85DlIKeW:-MVqAeag2jgOpnxORHPR:b-wlano0) ([raw file](https://github.com/eastgenomics/mutect2_vcf_2_bsvi/blob/445a956d4024b8a76ba5345f0f2f9af2385a1b24/README.md#L17)):*
<details><summary><i>Previously, woook wrote…</i></summary><blockquote>

I've put ./1 into BSVI and it accepts it. 
It treats it as 0 though so looks the same as 0/1 in BSVi - however, I agree that it would be less wrong in the VCF to have ./1

As long as ./1 doesn't break anything else.
</blockquote></details>

Decision was made to stick with 0/1, at least until downstream apps can be tested with ./1.
However readme still describes ./1, while code uses 0/1

**Review by mattgarner — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/mutect2_vcf_2_bsvi/1)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jethror1)

___
*[README.md, line 17 at r2](https://reviewable.io/reviews/eastgenomics/mutect2_vcf_2_bsvi/1#-MVaqYtpEndH85DlIKeW:-MVqB4Rc3PERcTwYn2zx:b-pichd9) ([raw file](https://github.com/eastgenomics/mutect2_vcf_2_bsvi/blob/445a956d4024b8a76ba5345f0f2f9af2385a1b24/README.md#L17)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

Decision was made to stick with 0/1, at least until downstream apps can be tested with ./1.
However readme still describes ./1, while code uses 0/1
</blockquote></details>

OK, readme now describes 0/1

**Pull request merged**
