### PR TITLE
Version v1.1.0 updated

### PR DESCRIPTION
**Pull request by carmelinacharalambous**
* Line 95 corrected  .vcf should be replaced with _ms.vcf not _ms

---
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/mutect2_vcf_2_bsvi/9)

### CODE REVIEW

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/mutect2_vcf_2_bsvi/9)* status: all files reviewed, 2 unresolved discussions (waiting on @carmelinacharalambous)

___
*[.DS_Store, line 0 at r1](https://reviewable.io/reviews/eastgenomics/mutect2_vcf_2_bsvi/9#-MWZKvs62XRgugrzFRDB:-MWZKvs62XRgugrzFRDC:b5k0apr) ([raw file](https://github.com/eastgenomics/mutect2_vcf_2_bsvi/blob/5f67ce6bdcd05d8a22d406c7367d65b28778d501/.DS_Store#L0)):*
This file should be removed - not part of the app
___
*[bin/mutect2_vcf_2_BSVI_v1.1.0.py, line 95 at r1](https://reviewable.io/reviews/eastgenomics/mutect2_vcf_2_bsvi/9#-MWZQTb83diO0lwkCUBo:-MWZQTb9E7WWPtSOaWw7:b-h1rbmx) ([raw file](https://github.com/eastgenomics/mutect2_vcf_2_bsvi/blob/5f67ce6bdcd05d8a22d406c7367d65b28778d501/bin/mutect2_vcf_2_BSVI_v1.1.0.py#L95)):*
> ```
>     fname = str(Path(input_vcf).name).replace(
>         '.vcf', '_ms.vcf').rstrip('.gz').replace('ngr_', '').replace('_markdup_recalibrated', '')
> ```
Could we add a comment to explain the reasoning for doing this and the intention. A before/after example filename might be useful

**Comment by carmelinacharalambous** [comment]
___
*[.DS_Store, line  at r1](https://reviewable.io/reviews/eastgenomics/mutect2_vcf_2_bsvi/9#-MWZKvs62XRgugrzFRDB:-MWZTKj7CRH1uQJfkWMX:bou2ir0) ([raw file](https://github.com/eastgenomics/mutect2_vcf_2_bsvi/blob/5f67ce6bdcd05d8a22d406c7367d65b28778d501/.DS_Store#L)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

This file should be removed - not part of the app
</blockquote></details>

yes will remove

**Comment by carmelinacharalambous** [comment]
___
*[bin/mutect2_vcf_2_BSVI_v1.1.0.py, line 95 at r1](https://reviewable.io/reviews/eastgenomics/mutect2_vcf_2_bsvi/9#-MWZQTb83diO0lwkCUBo:-MWZTPK-EftWpIwHJ9rL:b5nmc1g) ([raw file](https://github.com/eastgenomics/mutect2_vcf_2_bsvi/blob/5f67ce6bdcd05d8a22d406c7367d65b28778d501/bin/mutect2_vcf_2_BSVI_v1.1.0.py#L95)):*
<details><summary><i>Previously, mattgarner wrote…</i></summary><blockquote>

> ```
>     fname = str(Path(input_vcf).name).replace(
>         '.vcf', '_ms.vcf').rstrip('.gz').replace('ngr_', '').replace('_markdup_recalibrated', '')
> ```
Could we add a comment to explain the reasoning for doing this and the intention. A before/after example filename might be useful
</blockquote></details>

comment explaining vcf output name added

**Review by mattgarner — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/mutect2_vcf_2_bsvi/9)* status: all files reviewed, 2 unresolved discussions (waiting on @carmelinacharalambous)

___
*[.DS_Store, line  at r1](https://reviewable.io/reviews/eastgenomics/mutect2_vcf_2_bsvi/9#-MWZKvs62XRgugrzFRDB:-MWZg1jmA4kMmxNX7NW4:b-pakeru) ([raw file](https://github.com/eastgenomics/mutect2_vcf_2_bsvi/blob/5f67ce6bdcd05d8a22d406c7367d65b28778d501/.DS_Store#L)):*
<details><summary><i>Previously, carmelinacharalambous wrote…</i></summary><blockquote>

yes will remove 
</blockquote></details>

Still seems to exist
___
*[bin/.DS_Store, line 0 at r2](https://reviewable.io/reviews/eastgenomics/mutect2_vcf_2_bsvi/9#-MWZg3mu-6o3ibpoYLq0:-MWZg3mu-6o3ibpoYLq1:b-4j695c) ([raw file](https://github.com/eastgenomics/mutect2_vcf_2_bsvi/blob/d449141e8917ec121069ea56546931f9cef98fa6/bin/.DS_Store#L0)):*
This one was deleted though

**Review by mattgarner — APPROVED** [review]

**Pull request merged**
